import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { FiCrosshair, FiEdit3, FiEye, FiEyeOff, FiPlayCircle, FiRefreshCw, FiSave, FiX } from 'react-icons/fi';
import { postJson } from '../../lib/api';
import InventoryScene from './InventoryScene';

const clone = (value) => JSON.parse(JSON.stringify(value));
const settingFor = (product) => ({ color: product.color, visible: product.visible !== false, packaging: product.packaging.source === 'override' ? { representation: product.packaging.representation, ...(product.packaging.representation === 'tote' ? { capacityPerTote: product.packaging.capacity } : { unitsPerPallet: product.packaging.capacity }), packageLabel: product.packaging.packageLabel } : null });

function reflow(products) {
  if (!products.length) return [];
  const gap = 1.4; const area = products.reduce((sum, product) => sum + (product.footprint.width + gap) * (product.footprint.depth + gap), 0);
  const target = Math.max(24, ...products.map((product) => product.footprint.width), Math.ceil(Math.sqrt(area) * 1.35));
  let x = 0; let z = 0; let shelf = 0;
  const placed = products.map((product) => { if (x > 0 && x + product.footprint.width > target) { x = 0; z += shelf + gap; shelf = 0; } const next = { ...product, position: { x: x + product.footprint.width / 2, z: z + product.footprint.depth / 2 }, rotation: 0 }; x += product.footprint.width + gap; shelf = Math.max(shelf, product.footprint.depth); return next; });
  const minX = Math.min(...placed.map((p) => p.position.x - p.footprint.width / 2)); const maxX = Math.max(...placed.map((p) => p.position.x + p.footprint.width / 2)); const minZ = Math.min(...placed.map((p) => p.position.z - p.footprint.depth / 2)); const maxZ = Math.max(...placed.map((p) => p.position.z + p.footprint.depth / 2));
  return placed.map((product) => ({ ...product, position: { x: product.position.x - (minX + maxX) / 2, z: product.position.z - (minZ + maxZ) / 2 } }));
}

export default function InventoryPage() {
  const [data, setData] = useState({ products: [], hiddenProducts: [], floor: { width: 20, depth: 20 }, revision: '' });
  const [draft, setDraft] = useState([]); const [hiddenDraft, setHiddenDraft] = useState([]); const [editing, setEditing] = useState(false); const [selectedId, setSelectedId] = useState(null); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [focusSignal, setFocusSignal] = useState(0); const [resumeSignal, setResumeSignal] = useState(0); const [resetSignal, setResetSignal] = useState(0); const [orbiting, setOrbiting] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await postJson('getUniquemInventory', {}, { authed: true }); setData(result); setDraft(clone(result.products || [])); setHiddenDraft(clone(result.hiddenProducts || [])); } catch (reason) { setError(reason.message || 'Inventory could not be loaded.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const products = editing ? draft : data.products;
  const hiddenProducts = editing ? hiddenDraft : data.hiddenProducts;
  const selected = products.find((item) => item.productId === selectedId) || null;
  const browserItems = useMemo(() => { const term = query.trim().toLocaleLowerCase('en-CA'); return products.filter((item) => !term || `${item.item} ${item.description || ''}`.toLocaleLowerCase('en-CA').includes(term)); }, [products, query]);
  const select = (productId) => { setSelectedId(productId); setFocusSignal((value) => value + 1); };
  const replaceProduct = (productId, patch) => setDraft((current) => reflow(current.map((item) => item.productId === productId ? { ...item, ...patch } : item)));
  const begin = () => { setDraft(clone(data.products)); setHiddenDraft(clone(data.hiddenProducts)); setEditing(true); setNotice(''); setError(''); };
  const cancel = () => { setDraft(clone(data.products)); setHiddenDraft(clone(data.hiddenProducts)); setEditing(false); setError(''); };
  const save = async () => { setSaving(true); setError(''); try { const configurableHidden = hiddenDraft.filter((product) => product.canShow); const settings = Object.fromEntries([...draft, ...configurableHidden].map((product) => [product.productId, settingFor(product)])); const result = await postJson('saveUniquemInventoryLayout', { revision: data.revision, products: settings }, { authed: true }); setData(result); setDraft(clone(result.products)); setHiddenDraft(clone(result.hiddenProducts)); setEditing(false); setNotice('Product display settings saved.'); } catch (reason) { setError(reason.message || 'Display settings could not be saved.'); } finally { setSaving(false); } };
  const setPackaging = (field, value) => {
    if (!selected) return; const representation = field === 'representation' ? value : selected.packaging.representation; const capacity = field === 'capacity' ? Number(value) : (selected.packaging.capacity || 1); const packageLabel = field === 'packageLabel' ? value : selected.packaging.packageLabel;
    const packaging = { ...selected.packaging, representation, capacity, packageLabel, resolved: capacity > 0, inferred: false, source: 'override', warning: null };
    const loadCount = capacity > 0 ? Math.ceil(selected.quantityOnHand / capacity) : 1; const remainder = capacity > 0 ? selected.quantityOnHand % capacity : null; const stackCount = Math.ceil(loadCount / 3); const columns = Math.max(1, Math.ceil(Math.sqrt(stackCount))); const rows = Math.max(1, Math.ceil(stackCount / columns));
    replaceProduct(selected.productId, { packaging, loadCount, stackCount, columns, rows, stackLimit: 3, partial: remainder > 0, finalLoadQuantity: remainder || capacity, finalLoadPercent: capacity > 0 ? Math.round(((remainder || capacity) / capacity) * 1000) / 10 : null, footprint: { width: Math.max(1.2, columns * 1.35), depth: Math.max(1.2, rows * 1.35) } });
  };
  const hideSelected = () => { if (!selected) return; setDraft((current) => reflow(current.filter((item) => item.productId !== selected.productId))); setHiddenDraft((current) => [...current, { ...selected, visible: false, canShow: true, hiddenReason: 'Hidden from 3D by a user' }]); setSelectedId(null); };
  const showHidden = (product) => { setHiddenDraft((current) => current.filter((item) => item.productId !== product.productId)); setDraft((current) => reflow([...current, { ...product, visible: true }])); };

  return <div className="inventory-page">
    {error ? <div className="uniquem-alert" role="alert">{error}</div> : null}{notice ? <div className="uniquem-success">{notice}</div> : null}
    <header className="inventory-toolbar"><div><strong>{products.length} product blocks</strong><span>QuickBooks snapshot · {products.reduce((sum, item) => sum + item.loadCount, 0)} physical loads · {orbiting ? 'Orbiting selected product' : 'Manual camera'}</span></div><div className="uniquem-actions">
      <button className="secondary" type="button" onClick={() => setResetSignal((value) => value + 1)}><FiRefreshCw />Reset camera</button>{selected ? <><button className="secondary" type="button" onClick={() => setFocusSignal((value) => value + 1)}><FiCrosshair />Focus selected</button><button className="secondary" type="button" onClick={() => setResumeSignal((value) => value + 1)}><FiPlayCircle />Resume orbit</button></> : null}<button className="secondary" type="button" onClick={load} disabled={editing || loading}>Refresh data</button>
      {!editing ? <button type="button" onClick={begin}><FiEdit3 />Customize products</button> : <><button className="secondary" type="button" onClick={cancel}><FiX />Cancel</button><button type="button" onClick={save} disabled={saving}><FiSave />{saving ? 'Saving…' : 'Save changes'}</button></>}
    </div></header>
    <div className="inventory-workspace">
      <section className="inventory-stage-panel"><div className="inventory-scene-tools"><span>Mouse: drag to orbit · wheel to zoom · click to focus</span><span>Touch: one-finger orbit · pinch zoom · tap to focus</span></div>{loading ? <div className="inventory-loading">Loading 3D inventory…</div> : <InventoryScene products={products} floor={data.floor} selectedId={selectedId} onSelect={select} focusSignal={focusSignal} resumeSignal={resumeSignal} resetSignal={resetSignal} onOrbitChange={setOrbiting} />}
        <div className="inventory-legend"><span><i className="tote" />Totes · max 3 high</span><span><i className="pallet" />Palletized bags/pails · max 3 high</span><span><i className="unknown" />Packaging needed</span></div>
      </section>
      <aside className="inventory-sidebar" aria-label="Inventory details">
        <details className="inventory-browser" open><summary>Products ({browserItems.length})</summary><div className="inventory-browser-search"><input aria-label="Search inventory products" placeholder="Search products" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="inventory-browser-list">{browserItems.map((product) => <button type="button" className={product.productId === selectedId ? 'selected' : ''} key={product.productId} onClick={() => select(product.productId)}><i style={{ background: product.color }} /><span><strong>{product.item}</strong><small>{product.loadCount} loads · {product.quantityOnHand} {product.unitOfMeasure || ''}</small></span><FiCrosshair /></button>)}</div></details>
        {selected ? <section className="inventory-selected"><header><div><small>Selected product</small><h2>{selected.item}</h2></div>{editing ? <button className="secondary" type="button" onClick={hideSelected}><FiEyeOff />Hide</button> : null}</header><dl><div><dt>QuickBooks quantity</dt><dd>{selected.quantityOnHand} {selected.unitOfMeasure || ''}</dd></div><div><dt>3D loads</dt><dd>{selected.loadCount} · {selected.stackCount} stacks</dd></div><div><dt>Packaging</dt><dd>{selected.packaging.resolved ? `${selected.packaging.capacity} ${selected.packaging.packageLabel} per ${selected.packaging.representation}` : 'Needs configuration'}</dd></div>{selected.partial ? <div><dt>Partial final load</dt><dd>{selected.finalLoadQuantity} {selected.packaging.packageLabel} · {selected.finalLoadPercent}%</dd></div> : null}</dl>{selected.packaging.warning ? <p className="inventory-warning">{selected.packaging.warning}</p> : null}{editing ? <div className="inventory-editor"><label>Color<input aria-label="Product color" type="color" value={selected.color} onChange={(event) => replaceProduct(selected.productId, { color: event.target.value })} /></label><label>Representation<select value={selected.packaging.representation} onChange={(event) => setPackaging('representation', event.target.value)}><option value="tote">Tote</option><option value="pallet">Pallet</option></select></label><label>{selected.packaging.representation === 'tote' ? 'Litres per tote' : 'Units per pallet'}<input aria-label="Package capacity" type="number" min="0.01" step="0.01" value={selected.packaging.capacity || ''} onChange={(event) => setPackaging('capacity', event.target.value)} /></label><label>Package label<input value={selected.packaging.packageLabel || ''} onChange={(event) => setPackaging('packageLabel', event.target.value)} /></label></div> : null}</section> : <div className="inventory-sidebar-empty"><strong>Select a product</strong><span>Choose a name or tap its 3D block to focus and inspect it.</span></div>}
      </aside>
    </div>
    <details className="inventory-hidden"><summary>{hiddenProducts.length} products not shown in 3D</summary><div>{hiddenProducts.map((item) => <article key={item.productId}><div><strong>{item.item}</strong><span>{item.hiddenReason}</span></div>{item.canShow ? <button className="secondary" type="button" disabled={!editing} onClick={() => showHidden(item)}><FiEye />Show</button> : null}</article>)}</div></details>
  </div>;
}
