import React, { useMemo, useState } from 'react';
import { AttachmentList, DataTable, Drawer, entityAttachments, packageSummary, Panel, productLabel } from './UniquemShared';

function RecipeDrawer({ data, recipe, busy, onClose, onSave, onDelete }) {
  const [form, setForm] = useState(recipe || { name: '', outputProductId: '', notes: '', ingredients: [{ productId: '', amount: '' }] });
  const update = (index, patch) => setForm({ ...form, ingredients: form.ingredients.map((item, i) => i === index ? { ...item, ...patch } : item) });
  return <Drawer title={recipe ? 'Edit recipe' : 'Create recipe'} busy={busy} onClose={onClose}><form className="uniquem-product-drawer-form" onSubmit={(e) => { e.preventDefault(); onSave({ ...form, ingredients: form.ingredients.map((i) => ({ ...i, amount: Number(i.amount) })) }); }}>
    <label>Recipe name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Output product<select required value={form.outputProductId} onChange={(e) => setForm({ ...form, outputProductId: e.target.value })}><option value="">Select...</option>{data.products.map((p) => <option key={p.productId} value={p.productId}>{p.name}</option>)}</select><small>Ingredient amounts below are per one output package.</small></label>
    {form.ingredients.map((item, index) => { const p = data.products.find((x) => x.productId === item.productId); return <div className="uniquem-line-editor" key={index}><label>Ingredient<select required value={item.productId} onChange={(e) => update(index, { productId: e.target.value })}><option value="">Select...</option>{data.products.map((x) => <option key={x.productId} value={x.productId}>{x.name}</option>)}</select></label><label>Amount ({p?.measurementUnit || 'kg/L'})<input required min="0.001" step="0.001" type="number" value={item.amount} onChange={(e) => update(index, { amount: e.target.value })} /></label></div>; })}
    <button type="button" onClick={() => setForm({ ...form, ingredients: [...form.ingredients, { productId: '', amount: '' }] })}>Add ingredient</button><label>Notes<textarea value={form.notes || ''} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><button type="submit" disabled={busy}>Save recipe</button>{recipe ? <button className="uniquem-danger" type="button" disabled={busy} onClick={onDelete}>Delete recipe</button> : null}
  </form></Drawer>;
}

function RunDrawer({ data, lookups, run, busy, onClose, onSave, onComplete, onDelete }) {
  const readOnly = run?.status === 'completed'; const [form, setForm] = useState(run || { recipeId: '', outputPackages: '', warehouseId: '', location: 'Main', outputLotNumber: '', notes: '', allocations: [{ batchId: '', packageQuantity: '' }] }); const [files, setFiles] = useState([]);
  const recipe = data.recipes.find((r) => r.recipeId === form.recipeId); const warehouse = lookups.warehouses.get(form.warehouseId);
  const required = useMemo(() => (recipe?.ingredients || []).map((i) => ({ ...i, total: Number(i.amount) * Number(form.outputPackages || 0) })), [recipe, form.outputPackages]);
  const allocation = (index, patch) => setForm({ ...form, allocations: form.allocations.map((item, i) => i === index ? { ...item, ...patch } : item) });
  return <Drawer title={readOnly ? 'Completed production run' : run ? 'Edit production draft' : 'Create production draft'} busy={busy} onClose={onClose}><form className="uniquem-product-drawer-form" onSubmit={(e) => { e.preventDefault(); onSave({ ...form, outputPackages: Number(form.outputPackages), allocations: form.allocations.map((a) => ({ ...a, packageQuantity: Number(a.packageQuantity) })) }, files); }}>
    <label>Recipe<select required disabled={readOnly} value={form.recipeId} onChange={(e) => setForm({ ...form, recipeId: e.target.value })}><option value="">Select...</option>{data.recipes.map((r) => <option key={r.recipeId} value={r.recipeId}>{r.name}</option>)}</select></label><label>Output packages<input required readOnly={readOnly} min="0.001" step="0.001" type="number" value={form.outputPackages} onChange={(e) => setForm({ ...form, outputPackages: e.target.value })} /></label>
    {required.length ? <div className="uniquem-preview"><strong>Required ingredients</strong>{required.map((i) => <span key={i.productId}>{productLabel(lookups.products.get(i.productId))}: {i.total} {lookups.products.get(i.productId)?.measurementUnit}</span>)}</div> : null}
    <label>Output warehouse<select required disabled={readOnly} value={form.warehouseId} onChange={(e) => setForm({ ...form, warehouseId: e.target.value, location: 'Main' })}><option value="">Select...</option>{data.warehouses.map((w) => <option key={w.warehouseId} value={w.warehouseId}>{w.name}</option>)}</select></label><label>Output location<select disabled={readOnly} value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })}>{(warehouse?.locations || ['Main']).map((l) => <option key={l}>{l}</option>)}</select></label><label>Output lot<input readOnly={readOnly} value={form.outputLotNumber || ''} onChange={(e) => setForm({ ...form, outputLotNumber: e.target.value })} /></label>
    {(form.allocations || []).map((item, index) => <div className="uniquem-line-editor" key={index}><label>Source inventory<select required disabled={readOnly} value={item.batchId} onChange={(e) => allocation(index, { batchId: e.target.value })}><option value="">Select...</option>{data.batches.map((b) => <option key={b.batchId} value={b.batchId}>{productLabel(lookups.products.get(b.productId))} — {b.lotNumber || b.batchId.slice(0, 8)} — {b.packageQuantity} pkg</option>)}</select></label><label>Packages consumed<input required readOnly={readOnly} min="0.001" step="0.001" type="number" value={item.packageQuantity} onChange={(e) => allocation(index, { packageQuantity: e.target.value })} /></label></div>)}
    {!readOnly ? <button type="button" onClick={() => setForm({ ...form, allocations: [...form.allocations, { batchId: '', packageQuantity: '' }] })}>Add source inventory row</button> : null}<label>Notes<textarea readOnly={readOnly} value={form.notes || ''} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label>
    {!readOnly ? <><label>Batch sheets / photos<input type="file" multiple onChange={(e) => setFiles([...files, ...[...e.target.files].map((file) => ({ file, kind: file.type.startsWith('image/') ? 'image' : 'batch-sheet' }))])} /></label><button type="submit" disabled={busy}>Save draft</button>{run ? <><button type="button" disabled={busy} onClick={() => onComplete(run.runId)}>Complete run</button><button className="uniquem-danger" type="button" disabled={busy} onClick={() => onDelete(run.runId)}>Delete draft</button></> : null}</> : <><div className="uniquem-preview"><strong>Output</strong><span>{packageSummary(lookups.products.get(recipe?.outputProductId), form.outputPackages)}</span><span>Output batch: {run.outputBatchId}</span></div><AttachmentList attachments={entityAttachments(data, 'production-run', run.runId)} /></>}
  </form></Drawer>;
}

export default function ProductionPage({ data, lookups, mutate, uploadAttachment }) {
  const [drawer, setDrawer] = useState(null); const [busy, setBusy] = useState(false); const run = async (endpoint, payload, close = true) => { setBusy(true); const response = await mutate(endpoint, payload); setBusy(false); if (response && close) setDrawer(null); return response; };
  const saveRun = async (payload, files) => { const response = await run('saveUniquemProductionRun', payload); if (response?.runId) for (const item of files) await uploadAttachment({ ...item, entityType: 'production-run', entityId: response.runId }); };
  return <div className="uniquem-stack"><Panel title="Recipes" action={<button type="button" onClick={() => setDrawer({ type: 'recipe' })}>Create recipe</button>}><DataTable empty="No recipes yet." columns={['Recipe', 'Output product', 'Ingredients', '']} rows={data.recipes.map((r) => [r.name, productLabel(lookups.products.get(r.outputProductId)), (r.ingredients || []).map((i) => `${productLabel(lookups.products.get(i.productId))}: ${i.amount} ${lookups.products.get(i.productId)?.measurementUnit}`).join(', ') || '-', <button type="button" onClick={() => setDrawer({ type: 'recipe', recipe: r })}>Edit</button>])} /></Panel><Panel title="Production runs" action={<button type="button" onClick={() => setDrawer({ type: 'run' })}>Create production run</button>}><DataTable empty="No production runs yet." columns={['Created', 'Recipe', 'Output', 'Destination', 'Status']} rows={data.productionRuns.map((r) => [r.createdAt?.slice(0, 10) || '-', <button className="uniquem-link-button" type="button" onClick={() => setDrawer({ type: 'run', run: r })}>{data.recipes.find((x) => x.recipeId === r.recipeId)?.name || r.recipeId}</button>, `${r.outputPackages} packages`, `${lookups.warehouses.get(r.warehouseId)?.name} / ${r.location}`, r.status])} /></Panel>
    {drawer?.type === 'recipe' ? <RecipeDrawer data={data} recipe={drawer.recipe} busy={busy} onClose={() => setDrawer(null)} onSave={(p) => run('saveUniquemRecipe', p)} onDelete={() => window.confirm('Delete this unused recipe?') && run('deleteUniquemRecipe', { recipeId: drawer.recipe.recipeId })} /> : null}
    {drawer?.type === 'run' ? <RunDrawer data={data} lookups={lookups} run={drawer.run} busy={busy} onClose={() => setDrawer(null)} onSave={saveRun} onComplete={(runId) => window.confirm('Complete this run and post inventory changes?') && run('completeUniquemProductionRun', { runId })} onDelete={(runId) => window.confirm('Delete this draft?') && run('deleteUniquemProductionRun', { runId })} /> : null}
  </div>;
}
