import React, { useState } from 'react';
import { AttachmentList, DataTable, Drawer, entityAttachments, packageSummary, Panel, productLabel, today } from './UniquemShared';

const empty = { productId: '', warehouseId: '', location: 'Main', packageQuantity: '', lotNumber: '', supplier: '', supplierReference: '', receivedDate: today(), expiryDate: '', notes: '' };
function ReceiptDrawer({ data, lookups, receipt, busy, onClose, onCreate }) {
  const [form, setForm] = useState(empty); const [files, setFiles] = useState([]); const set = (key, value) => setForm({ ...form, [key]: value });
  if (receipt) { const product = lookups.products.get(receipt.productId); return <Drawer title="Receipt details" onClose={onClose}><div className="uniquem-product-view"><h3>{productLabel(product)}</h3><p>{packageSummary(product, receipt.packageQuantity)}</p><div className="uniquem-meta-grid"><span>Supplier: <strong>{receipt.supplier || '-'}</strong></span><span>Reference: <strong>{receipt.supplierReference || '-'}</strong></span><span>Destination: <strong>{lookups.warehouses.get(receipt.warehouseId)?.name} / {receipt.location}</strong></span><span>Lot: <strong>{receipt.lotNumber || '-'}</strong></span><span>Received: <strong>{receipt.receivedDate}</strong></span><span>Expiry: <strong>{receipt.expiryDate || '-'}</strong></span></div><p>{receipt.notes}</p><AttachmentList attachments={entityAttachments(data, 'receipt', receipt.receiptId)} /></div></Drawer>; }
  const warehouse = lookups.warehouses.get(form.warehouseId);
  return <Drawer title="Create receipt" busy={busy} onClose={onClose}><form className="uniquem-product-drawer-form" onSubmit={(e) => { e.preventDefault(); onCreate({ ...form, packageQuantity: Number(form.packageQuantity) }, files); }}>
    <label>Product<select required value={form.productId} onChange={(e) => set('productId', e.target.value)}><option value="">Select...</option>{data.products.map((p) => <option key={p.productId} value={p.productId}>{p.name}</option>)}</select></label>
    <label>Warehouse<select required value={form.warehouseId} onChange={(e) => { setForm({ ...form, warehouseId: e.target.value, location: 'Main' }); }}><option value="">Select...</option>{data.warehouses.map((w) => <option key={w.warehouseId} value={w.warehouseId}>{w.name}</option>)}</select></label>
    <label>Location<select value={form.location} onChange={(e) => set('location', e.target.value)}>{(warehouse?.locations || ['Main']).map((l) => <option key={l}>{l}</option>)}</select></label>
    <label>Package quantity<input required min="0.001" step="0.001" type="number" value={form.packageQuantity} onChange={(e) => set('packageQuantity', e.target.value)} /></label>
    <label>Lot (optional)<input value={form.lotNumber} onChange={(e) => set('lotNumber', e.target.value)} /></label><label>Supplier<input value={form.supplier} onChange={(e) => set('supplier', e.target.value)} /></label><label>Supplier reference<input value={form.supplierReference} onChange={(e) => set('supplierReference', e.target.value)} /></label><label>Received date<input required type="date" value={form.receivedDate} onChange={(e) => set('receivedDate', e.target.value)} /></label><label>Expiry<input type="date" value={form.expiryDate} onChange={(e) => set('expiryDate', e.target.value)} /></label><label>Notes<textarea value={form.notes} onChange={(e) => set('notes', e.target.value)} /></label>
    {[['Photos', 'image', 'image/*'], ['Delivery ticket', 'delivery-ticket', '.pdf,image/*'], ['COA', 'coa', '.pdf,image/*']].map(([label, kind, accept]) => <label key={kind}>{label}<input type="file" multiple accept={accept} onChange={(e) => setFiles([...files, ...[...e.target.files].map((file) => ({ file, kind }))])} /></label>)}
    {files.length ? <small>{files.length} file(s) queued</small> : null}<button type="submit" disabled={busy}>{busy ? 'Posting...' : 'Post receipt'}</button>
  </form></Drawer>;
}
export default function ReceivingPage({ data, lookups, mutate, uploadAttachment }) {
  const [drawer, setDrawer] = useState(null); const [busy, setBusy] = useState(false);
  const create = async (payload, files) => { setBusy(true); const response = await mutate('createUniquemReceipt', payload); if (response?.receiptId) for (const item of files) await uploadAttachment({ ...item, entityType: 'receipt', entityId: response.receiptId }); setBusy(false); if (response) setDrawer(null); };
  return <div className="uniquem-stack"><Panel title="Receipts" action={<button type="button" onClick={() => setDrawer({})}>Create receipt</button>}><DataTable empty="No receipts yet." columns={['Date', 'Product', 'Supplier', 'Destination', 'Quantity', 'Lot', 'Status']} rows={data.receipts.map((r) => { const p = lookups.products.get(r.productId); return [r.receivedDate, <button className="uniquem-link-button" type="button" onClick={() => setDrawer({ receipt: r })}>{productLabel(p)}</button>, r.supplier || '-', `${lookups.warehouses.get(r.warehouseId)?.name} / ${r.location}`, packageSummary(p, r.packageQuantity), r.lotNumber || '-', r.status]; })} /></Panel>{drawer ? <ReceiptDrawer data={data} lookups={lookups} receipt={drawer.receipt} busy={busy} onClose={() => setDrawer(null)} onCreate={create} /> : null}</div>;
}
