import React, { useState } from 'react';
import { AttachmentList, DataTable, Drawer, entityAttachments, packageSummary, Panel, productLabel, today } from './UniquemShared';

const blank = { customer: '', destination: '', shippingDate: today(), referenceNumber: '', notes: '', lines: [{ batchId: '', packageQuantity: '' }] };
function ShipmentDrawer({ data, lookups, shipment, busy, onClose, onSave, onComplete, onDelete, uploadAttachment }) {
  const readOnly = shipment?.status === 'completed'; const [form, setForm] = useState(shipment ? { ...shipment, lines: shipment.lines || [] } : blank); const [files, setFiles] = useState([]);
  const line = (index, patch) => setForm({ ...form, lines: form.lines.map((item, i) => i === index ? { ...item, ...patch } : item) });
  return <Drawer title={readOnly ? 'Completed shipment' : shipment ? 'Edit shipment draft' : 'Create shipment draft'} busy={busy} onClose={onClose}><form className="uniquem-product-drawer-form" onSubmit={(e) => { e.preventDefault(); onSave({ ...form, lines: form.lines.map((x) => ({ ...x, packageQuantity: Number(x.packageQuantity) })) }, files); }}>
    <label>Customer<input required readOnly={readOnly} value={form.customer} onChange={(e) => setForm({ ...form, customer: e.target.value })} /></label><label>Destination<input readOnly={readOnly} value={form.destination} onChange={(e) => setForm({ ...form, destination: e.target.value })} /></label><label>Shipping date<input required readOnly={readOnly} type="date" value={form.shippingDate} onChange={(e) => setForm({ ...form, shippingDate: e.target.value })} /></label><label>Reference<input readOnly={readOnly} value={form.referenceNumber} onChange={(e) => setForm({ ...form, referenceNumber: e.target.value })} /></label>
    {(form.lines || []).map((item, index) => <div className="uniquem-line-editor" key={index}><label>Inventory batch<select required disabled={readOnly} value={item.batchId} onChange={(e) => line(index, { batchId: e.target.value })}><option value="">Select...</option>{data.batches.map((b) => <option key={b.batchId} value={b.batchId}>{productLabel(lookups.products.get(b.productId))} — {b.lotNumber || b.batchId.slice(0, 8)} — {b.packageQuantity} packages</option>)}</select></label><label>Packages<input required readOnly={readOnly} min="0.001" step="0.001" type="number" value={item.packageQuantity} onChange={(e) => line(index, { packageQuantity: e.target.value })} /></label></div>)}
    {!readOnly ? <button type="button" onClick={() => setForm({ ...form, lines: [...form.lines, { batchId: '', packageQuantity: '' }] })}>Add inventory row</button> : null}<label>Notes<textarea readOnly={readOnly} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label>
    {!readOnly ? <><label>Photos / bill of lading / files<input type="file" multiple onChange={(e) => setFiles([...files, ...[...e.target.files].map((file) => ({ file, kind: file.type.startsWith('image/') ? 'image' : 'other' }))])} /></label><button type="submit" disabled={busy}>Save draft</button>{shipment ? <><button type="button" disabled={busy} onClick={() => onComplete(shipment.shipmentId)}>Complete shipment</button><button className="uniquem-danger" type="button" disabled={busy} onClick={() => onDelete(shipment.shipmentId)}>Delete draft</button></> : null}</> : <><div className="uniquem-preview">{form.lines.map((l) => { const b = lookups.batches.get(l.batchId); return b ? <span key={l.batchId}>{productLabel(lookups.products.get(b.productId))}: {packageSummary(lookups.products.get(b.productId), l.packageQuantity)}</span> : null; })}</div><AttachmentList attachments={entityAttachments(data, 'shipment', shipment.shipmentId)} /></>}
  </form></Drawer>;
}
export default function ShippingPage({ data, lookups, mutate, uploadAttachment }) {
  const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const run = async (endpoint, payload) => { setBusy(true); const response = await mutate(endpoint, payload); setBusy(false); if (response) setSelected(null); return response; };
  const save = async (payload, files) => { const response = await run('saveUniquemShipment', payload); if (response?.shipmentId) for (const item of files) await uploadAttachment({ ...item, entityType: 'shipment', entityId: response.shipmentId }); };
  return <div className="uniquem-stack"><Panel title="Shipments" action={<button type="button" onClick={() => setSelected({ create: true })}>Create shipment</button>}><DataTable empty="No shipments yet." columns={['Date', 'Customer', 'Destination', 'Reference', 'Packages', 'Status']} rows={data.shipments.map((s) => [s.shippingDate, <button className="uniquem-link-button" type="button" onClick={() => setSelected(s)}>{s.customer}</button>, s.destination || '-', s.referenceNumber || '-', s.lines.reduce((n, l) => n + Number(l.packageQuantity), 0), s.status])} /></Panel>{selected ? <ShipmentDrawer data={data} lookups={lookups} shipment={selected.create ? null : selected} busy={busy} onClose={() => setSelected(null)} onSave={save} uploadAttachment={uploadAttachment} onComplete={(shipmentId) => window.confirm('Complete this shipment and deduct inventory?') && run('completeUniquemShipment', { shipmentId })} onDelete={(shipmentId) => window.confirm('Delete this draft?') && run('deleteUniquemShipment', { shipmentId })} /> : null}</div>;
}
