import test from 'node:test';
import assert from 'node:assert/strict';
import * as functions from './index.js';

const EXPECTED_EXPORTS = [
  'acceptInvite',
  'adjustUniquemInventory',
  'adminCancelInvite',
  'adminInviteUser',
  'adminListUsers',
  'adminResendInvite',
  'adminUpdateInvite',
  'adminUpdateUserAccess',
  'archiveAccountingCustomer',
  'archiveAccountingProduct',
  'archiveThreeDModel',
  'archiveUniquemAttachment',
  'completeUniquemProductionRun',
  'completeUniquemShipment',
  'createAccountingSamples',
  'createThreeDModel',
  'createUniquemAttachmentUpload',
  'createUniquemReceipt',
  'deleteUniquemProduct',
  'deleteUniquemProductionRun',
  'deleteUniquemRecipe',
  'deleteUniquemShipment',
  'deleteUniquemWarehouse',
  'exportAccountingCustomersIif',
  'exportAccountingProductsIif',
  'generateThreeDScene',
  'getThreeDModel',
  'listAccountingWorkspace',
  'listThreeDModels',
  'listUniquemAttachments',
  'listUniquemWorkspace',
  'previewInvite',
  'restoreThreeDModelVersion',
  'reviseThreeDModel',
  'runStartupDiagnostics',
  'saveAccountingCustomer',
  'saveAccountingProduct',
  'saveAccountingSettings',
  'saveUniquemAttachment',
  'saveUniquemProduct',
  'saveUniquemProductionRun',
  'saveUniquemRecipe',
  'saveUniquemShipment',
  'saveUniquemWarehouse',
  'updateAccountingExportStatus',
];

test('deployment entry point exposes the exact production Function contract', () => {
  assert.deepEqual(Object.keys(functions).sort(), EXPECTED_EXPORTS);
});
