import { randomUUID } from 'node:crypto';
import { admin, db } from '../../core/firebase.js';
import { miniAppHandler } from '../../core/http.js';

const ITEMS = 'uniquemItems'; const BUILDS = 'uniquemAssemblyBuilds'; const PAGE_SIZE = 50; const TOLERANCE = 1e-6; const handler = (work) => miniAppHandler('uniquem', work);
const clean = (value, max = 2000) => String(value ?? '').trim().slice(0, max); const finite = (value) => typeof value === 'number' && Number.isFinite(value);
function invalid(message, status = 400) { throw Object.assign(new Error(message), { status }); }
function iso(value) { return value?.toDate ? value.toDate().toISOString() : value || null; }
function itemView(doc) { const v = doc.data() || {}; return { productId: v.productId || doc.id, item: v.item || '', description: v.description || '', active: v.active === true, activeStatus: v.active === true ? 'Active' : 'Inactive', unitOfMeasure: v.unitOfMeasure || '', quantityOnHand: Number(v.quantityOnHand) || 0, color: v.color || '#64748b', image: v.image || null, lastAssemblyComponents: v.lastAssemblyComponents || [] }; }
function buildView(doc) { const v = doc.data() || {}; return { ...v, buildId: v.buildId || doc.id, postedAt: iso(v.postedAt), reversedAt: iso(v.reversedAt) }; }
export const percentageTotal = (components = []) => components.reduce((sum, row) => sum + Number(row.percentage || 0), 0);
export const isCompletePercentage = (components) => Math.abs(percentageTotal(components) - 100) <= TOLERANCE;
export function componentPayload(value, outputProductId) { if (!Array.isArray(value) || !value.length || value.length > 100) invalid('Choose between 1 and 100 components.'); const ids = new Set(); const rows = value.map((row, index) => { const productId = clean(row?.productId, 160); const percentage = Number(row?.percentage); if (!productId || !finite(percentage) || percentage <= 0 || percentage > 100) invalid(`Component ${index + 1} requires a percentage above 0 and no more than 100.`); if (productId === outputProductId) invalid('The finished item cannot be its own component.'); if (ids.has(productId)) invalid('Each component may only be selected once.'); ids.add(productId); return { productId, percentage }; }); if (!isCompletePercentage(rows)) invalid(`Component percentages must total 100%. Current total is ${percentageTotal(rows)}%.`); return rows; }
function positive(value, label) { const result = Number(value); if (!finite(result) || result <= 0) invalid(`${label} must be positive.`); return result; }
function date(value) { const text = clean(value, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(text)) invalid('Build date is required.'); return text; }
async function itemsSnapshot(tx = null) { const query = db.collection(ITEMS).limit(5000); return tx ? tx.get(query) : query.get(); }

export const getUniquemAssemblyWorkspace = handler(async (req) => {
  const query = clean(req.body?.query, 160).toLowerCase(); const cursor = clean(req.body?.cursor, 160); const historyCursor = clean(req.body?.historyCursor, 160);
  const [itemSnap, buildSnap] = await Promise.all([itemsSnapshot(), db.collection(BUILDS).orderBy('postedAt', 'desc').limit(5000).get()]);
  const all = itemSnap.docs.map(itemView).filter((item) => item.active && (!query || `${item.item} ${item.description}`.toLowerCase().includes(query))).sort((a,b) => a.item.localeCompare(b.item)); const start = cursor ? Math.max(0, all.findIndex((x) => x.productId === cursor) + 1) : 0; const items = all.slice(start, start + PAGE_SIZE);
  const builds = buildSnap.docs.map(buildView); const hStart = historyCursor ? Math.max(0, builds.findIndex((x) => x.buildId === historyCursor) + 1) : 0; const history = builds.slice(hStart, hStart + PAGE_SIZE);
  return { items, nextCursor: start + PAGE_SIZE < all.length ? items.at(-1)?.productId : null, builds: history, nextHistoryCursor: hStart + PAGE_SIZE < builds.length ? history.at(-1)?.buildId : null };
});

export const postUniquemAssemblyBuild = handler(async (req, user) => {
  const outputProductId = clean(req.body?.outputProductId, 160); const outputQuantity = positive(req.body?.outputQuantity, 'Finished quantity'); const components = componentPayload(req.body?.components, outputProductId); let result;
  await db.runTransaction(async (tx) => {
    const snap = await itemsSnapshot(tx); const items = new Map(snap.docs.map((doc) => [doc.id, { doc, ...itemView(doc) }])); const output = items.get(outputProductId); if (!output?.active) invalid('Select an active finished item.', 409);
    for (const row of components) if (!items.get(row.productId)?.active) invalid('Every component must be active.', 409);
    const calculated = components.map((row) => ({ ...row, quantity: outputQuantity * row.percentage / 100 })); const movements = [...calculated.map((row) => ({ productId: row.productId, quantity: -row.quantity, role: 'component' })), { productId: outputProductId, quantity: outputQuantity, role: 'output' }];
    const shortages = movements.filter((move) => move.quantity < 0 && items.get(move.productId).quantityOnHand + move.quantity < 0).map((move) => ({ productId: move.productId, item: items.get(move.productId).item, current: items.get(move.productId).quantityOnHand, projected: items.get(move.productId).quantityOnHand + move.quantity })); if (shortages.length && req.body?.acknowledgeShortage !== true) invalid('Confirm that this build will create negative inventory.', 409);
    const now = admin.firestore.FieldValue.serverTimestamp(); for (const move of movements) tx.update(db.collection(ITEMS).doc(move.productId), { quantityOnHand: admin.firestore.FieldValue.increment(move.quantity), stockUpdatedAt: now, stockUpdatedBy: user.uid, updatedAt: now, updatedBy: user.uid });
    const componentSnapshots = calculated.map((row) => { const item = items.get(row.productId); return { ...row, item: item.item, unitOfMeasure: item.unitOfMeasure, color: item.color, image: item.image || null }; }); const buildId = randomUUID(); const build = { buildId, kind: 'build', status: 'Posted', outputProductId, outputItem: output.item, outputUnitOfMeasure: output.unitOfMeasure, outputColor: output.color, outputImage: output.image || null, outputQuantity, components: componentSnapshots, percentageTotal: 100, movements, shortages, buildDate: date(req.body?.buildDate), reference: clean(req.body?.reference,160), notes: clean(req.body?.notes), postedAt: now, postedBy: user.uid, postedByEmail: user.email || '' };
    tx.create(db.collection(BUILDS).doc(buildId), build); tx.update(db.collection(ITEMS).doc(outputProductId), { lastAssemblyComponents: components, lastAssemblyBuildId: buildId }); result = build;
  }); return { build: result };
});

export const reverseUniquemAssemblyBuild = handler(async (req, user) => {
  const buildId = clean(req.body?.buildId,160); const reason = clean(req.body?.reason,2000); if (!reason) invalid('Reversal reason is required.'); let result;
  await db.runTransaction(async (tx) => { const buildRef = db.collection(BUILDS).doc(buildId); const buildSnap = await tx.get(buildRef); if (!buildSnap.exists) invalid('Build no longer exists.',404); const build = buildSnap.data(); if (build.kind !== 'build' || build.status !== 'Posted' || build.reversalId) invalid('This build cannot be reversed again.',409); const itemSnap = await itemsSnapshot(tx); const items = new Map(itemSnap.docs.map((doc) => [doc.id,itemView(doc)])); const movements = build.movements.map((move) => ({ ...move, quantity: -move.quantity })); const shortages = movements.filter((move) => (items.get(move.productId)?.quantityOnHand || 0) + move.quantity < 0); if (shortages.length && req.body?.acknowledgeShortage !== true) invalid('Confirm that this reversal will create negative inventory.',409); const now = admin.firestore.FieldValue.serverTimestamp(); for (const move of movements) { if (!items.has(move.productId)) invalid('A referenced item no longer exists.',409); tx.update(db.collection(ITEMS).doc(move.productId), { quantityOnHand: admin.firestore.FieldValue.increment(move.quantity), stockUpdatedAt: now, stockUpdatedBy: user.uid, updatedAt: now, updatedBy: user.uid }); } const reversalId = randomUUID(); const reversal = { buildId: reversalId, kind: 'reversal', status: 'Posted', reversesBuildId: buildId, outputProductId: build.outputProductId, outputItem: build.outputItem, outputUnitOfMeasure: build.outputUnitOfMeasure, outputColor: build.outputColor, outputImage: build.outputImage || null, movements, shortages, buildDate: date(req.body?.buildDate), notes: reason, postedAt: now, postedBy: user.uid, postedByEmail: user.email || '' }; tx.create(db.collection(BUILDS).doc(reversalId), reversal); tx.update(buildRef, { status: 'Reversed', reversalId, reversedAt: now, reversedBy: user.uid }); result = reversal; }); return { build: result };
});

export const __testables = { componentPayload, percentageTotal, isCompletePercentage };
