import { db } from '../../core/firebase.js';
import { miniAppHandler } from '../../core/http.js';

const ITEMS = 'uniquemItems'; const ROW_GAP = 1.4; const MAX_LOADS = 2500; const handler = (work) => miniAppHandler('uniquem', work);
function invalid(message, status = 400) { throw Object.assign(new Error(message), { status }); }
export function primaryPackaging(item = {}) { const row = (item.packaging || []).find((value) => value.isPrimary); if (!row) return null; return { ...row, representation: row.type === 'tote' ? 'tote' : 'pallet', capacity: row.quantityPerPackage * row.packagesPerPallet, packageLabel: row.type === 'other' ? row.customLabel : row.type, resolved: true }; }
export function deterministicColor(productId = '') { let hash = 0; for (const char of String(productId)) hash = ((hash * 31) + char.charCodeAt(0)) >>> 0; return ['#0f766e','#2563eb','#7c3aed','#c2410c','#be123c','#4d7c0f','#0369a1','#a16207'][hash % 8]; }
export function calculateInventoryProduct(item) {
  const quantityOnHand = Number(item.quantityOnHand) || 0; const packaging = primaryPackaging(item); const visible = item.active === true && quantityOnHand > 0;
  if (!visible) return { productId: item.productId, item: item.item, description: item.description || '', active: item.active === true, activeStatus: item.active === true ? 'Active' : 'Inactive', quantityOnHand, unitOfMeasure: item.unitOfMeasure, color: item.color || deterministicColor(item.productId), image: item.image || null, packaging, allPackaging: item.packaging || [], visible: false, hiddenReason: item.active !== true ? 'Item is inactive' : 'Quantity On Hand is zero' };
  const loadCount = packaging ? Math.ceil(quantityOnHand / packaging.capacity) : 1; if (loadCount > MAX_LOADS) invalid(`${item.item} would create more than ${MAX_LOADS} loads. Increase its primary packaging capacity.`);
  const remainder = packaging ? quantityOnHand % packaging.capacity : 0; const finalLoadQuantity = packaging ? (remainder || packaging.capacity) : quantityOnHand; const stackCount = Math.ceil(loadCount / 3); const columns = Math.max(1, Math.ceil(Math.sqrt(stackCount))); const rows = Math.max(1, Math.ceil(stackCount / columns));
  return { productId: item.productId, item: item.item, description: item.description || '', active: true, activeStatus: 'Active', quantityOnHand, unitOfMeasure: item.unitOfMeasure, color: item.color || deterministicColor(item.productId), image: item.image || null, packaging: packaging || { representation: 'pallet', capacity: null, packageLabel: 'units', resolved: false }, allPackaging: item.packaging || [], visible: true, loadCount, stackCount, stackLimit: 3, columns, rows, partial: Boolean(packaging && remainder), finalLoadQuantity, finalLoadPercent: packaging ? Math.round(finalLoadQuantity / packaging.capacity * 1000) / 10 : null, footprint: { width: Math.max(1.2, columns * 1.35), depth: Math.max(1.2, rows * 1.35) }, position: null, rotation: 0 };
}
function rotated(product) { return product.rotation % 180 === 0 ? product.footprint : { width: product.footprint.depth, depth: product.footprint.width }; }
export function autoPlaceProducts(products = []) { if (!products.length) return []; const total = products.reduce((sum,p) => sum + (p.footprint.width + ROW_GAP) * (p.footprint.depth + ROW_GAP),0); const target = Math.max(24,Math.ceil(Math.sqrt(total)*1.35)); let x=0,z=0,depth=0; const placed=products.map((p)=>{ if(x>0&&x+p.footprint.width>target){x=0;z+=depth+ROW_GAP;depth=0;} const n={...p,position:{x:x+p.footprint.width/2,z:z+p.footprint.depth/2}};x+=p.footprint.width+ROW_GAP;depth=Math.max(depth,p.footprint.depth);return n;}); const minX=Math.min(...placed.map(p=>p.position.x-p.footprint.width/2)),maxX=Math.max(...placed.map(p=>p.position.x+p.footprint.width/2)),minZ=Math.min(...placed.map(p=>p.position.z-p.footprint.depth/2)),maxZ=Math.max(...placed.map(p=>p.position.z+p.footprint.depth/2)); return placed.map(p=>({...p,position:{x:p.position.x-(minX+maxX)/2,z:p.position.z-(minZ+maxZ)/2}})); }
export function buildInventory(items = []) { const calculated=items.map(calculateInventoryProduct); const products=autoPlaceProducts(calculated.filter(x=>x.visible).sort((a,b)=>a.item.localeCompare(b.item))); const hiddenProducts=calculated.filter(x=>!x.visible).sort((a,b)=>a.item.localeCompare(b.item)); const maxX=products.reduce((m,p)=>Math.max(m,Math.abs(p.position.x)+rotated(p).width/2),10),maxZ=products.reduce((m,p)=>Math.max(m,Math.abs(p.position.z)+rotated(p).depth/2),10); return { products, hiddenProducts, floor:{width:Math.ceil((maxX*2+8)/5)*5,depth:Math.ceil((maxZ*2+8)/5)*5} }; }
export const getUniquemInventory = handler(async () => { const snap=await db.collection(ITEMS).limit(5000).get(); const items=snap.docs.map(doc=>({...doc.data(),productId:doc.data().productId||doc.id})); return buildInventory(items); });
export const __testables = { primaryPackaging };
